ezsp_device = "/dev/ttyUSB0"

[[devices]]
name = "outside"
device_id = "00:01:02:03:04:05:06:07"

[[devices]]
name = "room_1"
device_id = "00:01:02:03:04:05:06:07"

[[devices]]
name = "room_2"
device_id = "00:01:02:03:04:05:06:07"

[[devices]]
name = "room_3"
device_id = "00:01:02:03:04:05:06:07"
